[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


#exclude = ["**/node_modules/"] # I've tried to put this in the "packages" key but not sure it works.


[tool.black]
exclude = '(\.eggs|\.git|\.venv|\venv|node_modules/)'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pylint.'MESSAGES CONTROL']
disable = "fixme,C,R"
max-line-length = 88

[tool.poe.executor]
type = "virtualenv"
location = ".venv"

[tool.poe.tasks]
black = "black ."
black_check = "black --check ."
isort = "isort ."
pylint = "pylint openflexure_microscope"
mypy = "mypy --cobertura-xml-report openflexure_microscope openflexure_microscope"
test = "pytest ."

format = ["black", "isort"]
lint = ["pylint", "mypy"]

check = ["format", "lint", "test"]